In [369]:
import pandas as pd
import numpy as np
orders = pd.read_csv(r"C:\Users\ashar\Downloads\ecommerce_sales_customer_analytics_150k.csv")
order_items = pd.read_csv(r"C:\Users\ashar\Downloads\order_items.csv")
product_catalog = pd.read_csv(r"C:\Users\ashar\Downloads\product_catalog.csv")
customer_master = pd.read_csv(r"C:\Users\ashar\Downloads\customer_master.csv")

In [370]:
datasets = {
    "orders": orders,
    "order_items": order_items,
    "product_catalog": product_catalog,
    "customer_master": customer_master
}

for name, df in datasets.items():
    print(f"\n{'='*60}")
    print(f"{name.upper()}")
    print(f"{'='*60}")
    print("Shape:", df.shape)
    print("\nColumns:")
    print(df.columns.tolist())

============================================================
ORDERS
============================================================
Shape: (138116, 46)

Columns:
['order_id', 'order_date', 'order_time', 'order_status', 'sales_channel', 'customer_id', 'customer_name', 'customer_age', 'gender', 'customer_segment', 'customer_type', 'customer_city', 'customer_state', 'customer_country', 'region', 'customer_postal_code', 'payment_method', 'payment_status', 'currency', 'shipping_method', 'warehouse', 'delivery_days', 'estimated_delivery_days', 'delivery_status', 'return_status', 'return_reason', 'customer_rating', 'review_sentiment', 'customer_review', 'marketing_channel', 'campaign_name', 'coupon_code', 'loyalty_points_earned', 'loyalty_points_redeemed', 'quantity', 'gross_sales', 'discount_amount', 'tax_amount', 'shipping_cost', 'net_sales', 'product_cost', 'profit', 'profit_margin_percentage', 'customer_lifetime_value', 'is_repeat_customer', 'customer_order_count']

============================================================
ORDER_ITEMS
============================================================
Shape: (397569, 12)

Columns:
['order_id', 'product_id', 'quantity', 'unit_price', 'discount_percentage', 'discount_amount', 'gross_sales', 'tax_amount', 'shipping_cost', 'net_sales', 'product_cost', 'profit']

============================================================
PRODUCT_CATALOG
============================================================
Shape: (1175, 9)

Columns:
['product_id', 'product_name', 'product_category', 'product_subcategory', 'brand', 'supplier', 'unit_price', 'product_cost', 'product_rating']

============================================================
CUSTOMER_MASTER
============================================================
Shape: (25000, 11)

Columns:
['customer_id', 'customer_name', 'customer_age', 'gender', 'customer_segment', 'customer_city', 'customer_state', 'customer_country', 'region', 'customer_postal_code', 'customer_acquisition_cost']

In [371]:
for name, df in datasets.items():
    print(f"\n{name.upper()}")
    print(df.dtypes)

ORDERS
order_id                     object
order_date                   object
order_time                   object
order_status                 object
sales_channel                object
customer_id                  object
customer_name                object
customer_age                  int64
gender                       object
customer_segment             object
customer_type                object
customer_city                object
customer_state               object
customer_country             object
region                       object
customer_postal_code          int64
payment_method               object
payment_status               object
currency                     object
shipping_method              object
warehouse                    object
delivery_days               float64
estimated_delivery_days     float64
delivery_status              object
return_status                object
return_reason                object
customer_rating             float64
review_sentiment             object
customer_review              object
marketing_channel            object
campaign_name                object
coupon_code                  object
loyalty_points_earned         int64
loyalty_points_redeemed       int64
quantity                      int64
gross_sales                 float64
discount_amount             float64
tax_amount                  float64
shipping_cost               float64
net_sales                   float64
product_cost                float64
profit                      float64
profit_margin_percentage    float64
customer_lifetime_value     float64
is_repeat_customer             bool
customer_order_count          int64
dtype: object

ORDER_ITEMS
order_id                object
product_id              object
quantity                 int64
unit_price             float64
discount_percentage    float64
discount_amount        float64
gross_sales            float64
tax_amount             float64
shipping_cost          float64
net_sales              float64
product_cost           float64
profit                 float64
dtype: object

PRODUCT_CATALOG
product_id              object
product_name            object
product_category        object
product_subcategory     object
brand                   object
supplier                object
unit_price             float64
product_cost           float64
product_rating         float64
dtype: object

CUSTOMER_MASTER
customer_id                   object
customer_name                 object
customer_age                   int64
gender                        object
customer_segment              object
customer_city                 object
customer_state                object
customer_country              object
region                        object
customer_postal_code           int64
customer_acquisition_cost    float64
dtype: object

In [372]:
for name, df in datasets.items():
    print(f"{name}: {df.duplicated().sum()} duplicate rows")

orders: 0 duplicate rows
order_items: 0 duplicate rows
product_catalog: 0 duplicate rows
customer_master: 0 duplicate rows

In [373]:
print("Order items duplicate rows:",
      order_items.duplicated().sum())

print("Unique orders:",
      order_items['order_id'].nunique())

print("Unique products:",
      order_items['product_id'].nunique())

Order items duplicate rows: 0
Unique orders: 138116
Unique products: 1175

In [374]:
print("Duplicate product_id:",
      product_catalog['product_id'].duplicated().sum())

Duplicate product_id: 0

In [375]:
print("Duplicate customer_id:",
      customer_master['customer_id'].duplicated().sum())

Duplicate customer_id: 0

In [376]:
for name, df in datasets.items():
    missing = pd.DataFrame({
        'missing_count': df.isnull().sum(),
        'missing_percentage': (df.isnull().sum() / len(df)) * 100
    })
    
    missing = missing[missing['missing_count'] > 0]
    missing = missing.sort_values('missing_percentage', ascending=False)
    
    print(f"\n{name.upper()}")
    print(missing)

ORDERS
                         missing_count  missing_percentage
return_status                   128654           93.149237
return_reason                   128654           93.149237
coupon_code                     110502           80.006661
campaign_name                    83233           60.263112
delivery_days                    24557           17.779982
customer_rating                  24557           17.779982
estimated_delivery_days          24557           17.779982
customer_review                  24557           17.779982
review_sentiment                 24557           17.779982

ORDER_ITEMS
Empty DataFrame
Columns: [missing_count, missing_percentage]
Index: []

PRODUCT_CATALOG
Empty DataFrame
Columns: [missing_count, missing_percentage]
Index: []

CUSTOMER_MASTER
Empty DataFrame
Columns: [missing_count, missing_percentage]
Index: []

In [377]:
orders = orders.drop(
    columns=['campaign_name', 'coupon_code']
)

In [378]:
orders['return_status'] = orders['return_status'].fillna(
    'Not Returned'
)

orders['return_reason'] = orders['return_reason'].fillna(
    'Not Applicable'
)

In [379]:
orders['review_sentiment'] = orders['review_sentiment'].fillna(
    'No Review'
)

orders['customer_review'] = orders['customer_review'].fillna(
    'No Review'
)

In [380]:
orders.isnull().sum().sort_values(ascending=False)

customer_rating             24557
delivery_days               24557
estimated_delivery_days     24557
order_id                        0
sales_channel                   0
customer_id                     0
customer_name                   0
customer_age                    0
gender                          0
order_date                      0
order_time                      0
order_status                    0
customer_city                   0
customer_type                   0
customer_segment                0
customer_state                  0
payment_method                  0
customer_country                0
region                          0
customer_postal_code            0
shipping_method                 0
currency                        0
payment_status                  0
warehouse                       0
delivery_status                 0
return_status                   0
return_reason                   0
review_sentiment                0
customer_review                 0
marketing_channel               0
loyalty_points_earned           0
loyalty_points_redeemed         0
quantity                        0
gross_sales                     0
discount_amount                 0
tax_amount                      0
shipping_cost                   0
net_sales                       0
product_cost                    0
profit                          0
profit_margin_percentage        0
customer_lifetime_value         0
is_repeat_customer              0
customer_order_count            0
dtype: int64

In [381]:
print(orders.columns.tolist())

['order_id', 'order_date', 'order_time', 'order_status', 'sales_channel', 'customer_id', 'customer_name', 'customer_age', 'gender', 'customer_segment', 'customer_type', 'customer_city', 'customer_state', 'customer_country', 'region', 'customer_postal_code', 'payment_method', 'payment_status', 'currency', 'shipping_method', 'warehouse', 'delivery_days', 'estimated_delivery_days', 'delivery_status', 'return_status', 'return_reason', 'customer_rating', 'review_sentiment', 'customer_review', 'marketing_channel', 'loyalty_points_earned', 'loyalty_points_redeemed', 'quantity', 'gross_sales', 'discount_amount', 'tax_amount', 'shipping_cost', 'net_sales', 'product_cost', 'profit', 'profit_margin_percentage', 'customer_lifetime_value', 'is_repeat_customer', 'customer_order_count']

In [382]:
categorical_columns = [
    'order_status',
    'sales_channel',
    'gender',
    'customer_segment',
    'customer_type',
    'customer_state',
    'region',
    'payment_method',
    'payment_status',
    'shipping_method',
    'warehouse',
    'delivery_status',
    'return_status',
    'return_reason',
    'review_sentiment',
    'marketing_channel',
    'is_repeat_customer'
]

for col in categorical_columns:
    print(f"\n--- {col} ---")
    print(orders[col].value_counts(dropna=False))

--- order_status ---
order_status
Completed    113559
Returned       9462
Cancelled      8398
Pending        6697
Name: count, dtype: int64

--- sales_channel ---
sales_channel
Mobile App      55318
Website         48237
Marketplace     20698
Social Media    13863
Name: count, dtype: int64

--- gender ---
gender
Female        66439
Male          66284
Non-Binary     5393
Name: count, dtype: int64

--- customer_segment ---
customer_segment
Consumer    75636
Premium     34746
VIP         13957
Business    13777
Name: count, dtype: int64

--- customer_type ---
customer_type
Loyal        129447
Returning      8335
New             334
Name: count, dtype: int64

--- customer_state ---
customer_state
Pennsylvania         9148
California           8523
New York             8431
Georgia              8384
Michigan             8227
Ohio                 8207
Texas                8048
Illinois             8017
North Carolina       7874
Florida              7741
England              5213
Northern Ireland     5168
Scotland             4933
Wales                4921
North Rhine          2507
Baden-Württemberg    2344
Hesse                2310
Lower Saxony         2231
Bavaria              2201
British Columbia     1583
South Australia      1530
New South Wales      1457
Alberta              1452
Manitoba             1414
Western Australia    1412
Victoria             1353
Quebec               1287
Ontario              1279
Karnataka            1218
Uttar Pradesh        1209
Tamil Nadu           1121
Dubai                1104
Maharashtra          1097
Abu Dhabi            1072
Gujarat              1062
Queensland           1042
Sharjah              1041
Ajman                 955
Name: count, dtype: int64

--- region ---
region
South      43990
Central    29627
West       26273
East       21602
North      16624
Name: count, dtype: int64

--- payment_method ---
payment_method
Credit Card          41460
Debit Card           27635
PayPal               20750
Digital Wallet       16382
Cash on Delivery     13863
Buy Now Pay Later    11061
Bank Transfer         6965
Name: count, dtype: int64

--- payment_status ---
payment_status
Paid        104250
Pending      13975
Failed       10429
Refunded      9462
Name: count, dtype: int64

--- shipping_method ---
shipping_method
Standard    62006
Express     34373
Economy     27824
Same Day    13913
Name: count, dtype: int64

--- warehouse ---
warehouse
WH-014    7447
WH-017    7389
WH-004    7384
WH-006    7345
WH-011    7314
WH-003    7305
WH-012    7305
WH-019    7298
WH-015    7294
WH-007    7294
WH-016    7271
WH-009    7239
WH-005    7236
WH-008    7206
WH-001    7199
WH-013    7174
WH-002    7154
WH-010    7139
WH-018    7123
Name: count, dtype: int64

--- delivery_status ---
delivery_status
On Time      86916
Cancelled    24557
Delayed      16886
Early         9757
Name: count, dtype: int64

--- return_status ---
return_status
Not Returned    128654
Returned          9462
Name: count, dtype: int64

--- return_reason ---
return_reason
Not Applicable             128654
Wrong Product                1237
Other                        1208
Changed Mind                 1204
Size Issue                   1182
Defective Product            1174
Late Delivery                1172
Product Not as Expected      1147
Damaged Product              1138
Name: count, dtype: int64

--- review_sentiment ---
review_sentiment
Positive     78083
Neutral      34684
No Review    24557
Negative       792
Name: count, dtype: int64

--- marketing_channel ---
marketing_channel
Organic Search     27742
Google Ads         20633
Direct             20515
Facebook Ads       16651
Instagram          13801
Email Marketing    11218
Referral           11191
Affiliate           6848
TikTok              5437
YouTube             4080
Name: count, dtype: int64

--- is_repeat_customer ---
is_repeat_customer
True     137782
False       334
Name: count, dtype: int64

In [383]:
print(orders['order_time'].head(20))

print("\nUnique time examples:")
print(
    orders['order_time']
    .dropna()
    .astype(str)
    .head(20)
    .tolist()
)

0     16:37:47
1     01:22:36
2     14:24:21
3     07:20:26
4     09:46:21
5     10:05:47
6     02:55:44
7     21:19:50
8     17:22:52
9     18:38:32
10    18:20:55
11    10:30:17
12    04:27:09
13    22:09:12
14    19:49:42
15    21:59:35
16    02:13:38
17    19:38:47
18    04:27:49
19    11:19:10
Name: order_time, dtype: object

Unique time examples:
['16:37:47', '01:22:36', '14:24:21', '07:20:26', '09:46:21', '10:05:47', '02:55:44', '21:19:50', '17:22:52', '18:38:32', '18:20:55', '10:30:17', '04:27:09', '22:09:12', '19:49:42', '21:59:35', '02:13:38', '19:38:47', '04:27:49', '11:19:10']

In [384]:
print(orders['order_time'].head(20))
print(orders['order_time'].dtype)

0     16:37:47
1     01:22:36
2     14:24:21
3     07:20:26
4     09:46:21
5     10:05:47
6     02:55:44
7     21:19:50
8     17:22:52
9     18:38:32
10    18:20:55
11    10:30:17
12    04:27:09
13    22:09:12
14    19:49:42
15    21:59:35
16    02:13:38
17    19:38:47
18    04:27:49
19    11:19:10
Name: order_time, dtype: object
object

In [385]:
# Convert order_date to datetime
orders['order_date'] = pd.to_datetime(
    orders['order_date'],
    errors='coerce'
)

In [386]:
print("Minimum order date:", orders['order_date'].min())
print("Maximum order date:", orders['order_date'].max())

print(
    "Invalid order dates:",
    orders['order_date'].isna().sum()
)

Minimum order date: 2021-01-01 00:00:00
Maximum order date: 2025-12-31 00:00:00
Invalid order dates: 0

In [387]:
print(
    "Invalid order dates:",
    orders['order_date'].isna().sum()
)

Invalid order dates: 0

In [388]:
orders['order_time'] = pd.to_datetime(
    orders['order_time'],
    format='%H:%M:%S',
    errors='coerce'
).dt.time

In [389]:
orders['order_time'].head(10)

0    16:37:47
1    01:22:36
2    14:24:21
3    07:20:26
4    09:46:21
5    10:05:47
6    02:55:44
7    21:19:50
8    17:22:52
9    18:38:32
Name: order_time, dtype: object

In [390]:
orders['order_year'] = orders['order_date'].dt.year
orders['order_month'] = orders['order_date'].dt.month
orders['order_month_name'] = orders['order_date'].dt.month_name()
orders['order_quarter'] = orders['order_date'].dt.quarter
orders['order_day'] = orders['order_date'].dt.day
orders['order_day_name'] = orders['order_date'].dt.day_name()

In [391]:
orders[
    [
        'gross_sales',
        'discount_amount',
        'tax_amount',
        'shipping_cost',
        'net_sales',
        'product_cost',
        'profit'
    ]
].describe()

,gross_sales,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit
count,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000
mean,1375.384176,237.621614,122.462933,22.278080,1282.503575,708.903449,551.322046
std,1291.009554,378.779459,140.939368,16.022739,1169.274669,730.044970,516.300936
min,6.310000,0.000000,0.340000,0.000000,5.800000,1.970000,-1281.590000
25%,458.920000,26.327500,34.650000,9.820000,448.200000,207.667500,190.757500
50%,995.730000,103.285000,77.010000,19.190000,950.760000,478.955000,408.395000
75%,1871.200000,277.125000,156.200000,30.750000,1744.582500,953.762500,752.845000
max,16051.190000,6759.020000,2091.520000,149.520000,16218.000000,9963.410000,7083.680000

In [392]:
orders['delivery_variance'] = np.where(
    orders['delivery_days'].notna() &
    orders['estimated_delivery_days'].notna(),
    orders['delivery_days'] -
    orders['estimated_delivery_days'],
    np.nan
)

In [393]:
orders['delivery_performance'] = np.select(
    [
        orders['delivery_variance'] < 0,
        orders['delivery_variance'] == 0,
        orders['delivery_variance'] > 0
    ],
    [
        'Early',
        'On Time',
        'Late'
    ],
    default='Not Available'
)

In [394]:
# Rebuild datasets after cleaning
datasets = {
    "orders": orders,
    "order_items": order_items,
    "product_catalog": product_catalog,
    "customer_master": customer_master
}

# Final data-quality overview
for name, df in datasets.items():
    print(f"\n{'='*60}")
    print(name.upper())
    print(f"{'='*60}")
    
    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])
    print("Duplicate rows:", df.duplicated().sum())
    
    missing = df.isnull().sum()
    missing = missing[missing > 0].sort_values(ascending=False)
    
    print("\nMissing values:")
    
    if missing.empty:
        print("No missing values")
    else:
        print(missing)

============================================================
ORDERS
============================================================
Rows: 138116
Columns: 52
Duplicate rows: 0

Missing values:
delivery_days              24557
estimated_delivery_days    24557
customer_rating            24557
delivery_variance          24557
dtype: int64

============================================================
ORDER_ITEMS
============================================================
Rows: 397569
Columns: 12
Duplicate rows: 0

Missing values:
No missing values

============================================================
PRODUCT_CATALOG
============================================================
Rows: 1175
Columns: 9
Duplicate rows: 0

Missing values:
No missing values

============================================================
CUSTOMER_MASTER
============================================================
Rows: 25000
Columns: 11
Duplicate rows: 0

Missing values:
No missing values

In [395]:
# Orders → Customer Master

order_customer_ids = set(
    orders['customer_id'].dropna()
)

master_customer_ids = set(
    customer_master['customer_id'].dropna()
)

missing_customers = order_customer_ids - master_customer_ids

print(
    "Customer IDs missing from customer_master:",
    len(missing_customers)
)

Customer IDs missing from customer_master: 0

In [396]:
# Order Items → Product Catalog

item_product_ids = set(
    order_items['product_id'].dropna()
)

catalog_product_ids = set(
    product_catalog['product_id'].dropna()
)

missing_products = item_product_ids - catalog_product_ids

print(
    "Product IDs missing from product_catalog:",
    len(missing_products)
)

Product IDs missing from product_catalog: 0

In [397]:
financial_columns = [
    'gross_sales',
    'discount_amount',
    'tax_amount',
    'shipping_cost',
    'net_sales',
    'product_cost',
    'profit',
    'profit_margin_percentage'
]

print("Financial Summary:")
display(orders[financial_columns].describe().T)

Financial Summary:

,count,mean,std,min,25%,50%,75%,max
gross_sales,138116.0,1375.384176,1291.009554,6.31,458.9200,995.730,1871.2000,16051.19
discount_amount,138116.0,237.621614,378.779459,0.00,26.3275,103.285,277.1250,6759.02
tax_amount,138116.0,122.462933,140.939368,0.34,34.6500,77.010,156.2000,2091.52
shipping_cost,138116.0,22.278080,16.022739,0.00,9.8200,19.190,30.7500,149.52
net_sales,138116.0,1282.503575,1169.274669,5.80,448.2000,950.760,1744.5825,16218.00
product_cost,138116.0,708.903449,730.044970,1.97,207.6675,478.955,953.7625,9963.41
profit,138116.0,551.322046,516.300936,-1281.59,190.7575,408.395,752.8450,7083.68
profit_margin_percentage,138116.0,45.065997,13.120357,-59.55,38.8800,46.990,53.7700,77.59

In [398]:
print("\nNegative values:")

for col in financial_columns:
    print(
        f"{col}:",
        (orders[col] < 0).sum()
    )

Negative values:
gross_sales: 0
discount_amount: 0
tax_amount: 0
shipping_cost: 0
net_sales: 0
product_cost: 0
profit: 1296
profit_margin_percentage: 1295

In [399]:
print("\nProfit Margin Summary:")
print(orders['profit_margin_percentage'].describe())

Profit Margin Summary:
count    138116.000000
mean         45.065997
std          13.120357
min         -59.550000
25%          38.880000
50%          46.990000
75%          53.770000
max          77.590000
Name: profit_margin_percentage, dtype: float64

In [400]:
# Validate profit margin calculation

orders['calculated_profit_margin'] = (
    orders['profit'] / orders['net_sales']
) * 100

orders['margin_difference'] = (
    orders['profit_margin_percentage']
    - orders['calculated_profit_margin']
)

print(
    "Maximum margin difference:",
    orders['margin_difference'].abs().max()
)

print(
    "Average margin difference:",
    orders['margin_difference'].abs().mean()
)

Maximum margin difference: 0.005000000000002558
Average margin difference: 0.0025023258356960732

In [401]:
print(
    orders[
        [
            'profit',
            'net_sales',
            'profit_margin_percentage',
            'calculated_profit_margin',
            'margin_difference'
        ]
    ].head(10)
)

    profit  net_sales  profit_margin_percentage  calculated_profit_margin  \
0   345.04     945.40                     36.50                 36.496721
1   -22.47    2018.41                     -1.11                 -1.113253
2   197.57     468.35                     42.18                 42.184264
3   247.83     546.52                     45.35                 45.346922
4  1530.36    2785.27                     54.94                 54.944763
5  1502.32    3375.24                     44.51                 44.510020
6   870.93    1691.87                     51.48                 51.477359
7   957.72    2393.58                     40.01                 40.012032
8   278.76     640.34                     43.53                 43.533123
9  1155.80    3094.63                     37.35                 37.348568

   margin_difference
0           0.003279
1           0.003253
2          -0.004264
3           0.003078
4          -0.004763
5          -0.000020
6           0.002641
7          -0.002032
8          -0.003123
9           0.001432

In [402]:
# Order Items → Orders

order_ids_orders = set(
    orders['order_id'].dropna()
)

order_ids_items = set(
    order_items['order_id'].dropna()
)

missing_orders = order_ids_items - order_ids_orders

print(
    "Order IDs in order_items but missing from orders:",
    len(missing_orders)
)

Order IDs in order_items but missing from orders: 0

In [403]:
print(
    orders.groupby('order_status')[
        [
            'delivery_days',
            'estimated_delivery_days',
            'customer_rating'
        ]
    ].apply(lambda x: x.isna().sum())
)

              delivery_days  estimated_delivery_days  customer_rating
order_status
Cancelled              8398                     8398             8398
Completed                 0                        0                0
Pending                6697                     6697             6697
Returned               9462                     9462             9462

In [404]:
print(
    orders.groupby('delivery_status')[
        [
            'delivery_days',
            'estimated_delivery_days'
        ]
    ].apply(lambda x: x.isna().sum())
)

                 delivery_days  estimated_delivery_days
delivery_status
Cancelled                24557                    24557
Delayed                      0                        0
Early                        0                        0
On Time                      0                        0

In [406]:
orders.isna().sum()

order_id                        0
order_date                      0
order_time                      0
order_status                    0
sales_channel                   0
customer_id                     0
customer_name                   0
customer_age                    0
gender                          0
customer_segment                0
customer_type                   0
customer_city                   0
customer_state                  0
customer_country                0
region                          0
customer_postal_code            0
payment_method                  0
payment_status                  0
currency                        0
shipping_method                 0
warehouse                       0
delivery_days               24557
estimated_delivery_days     24557
delivery_status                 0
return_status                   0
return_reason                   0
customer_rating             24557
review_sentiment                0
customer_review                 0
marketing_channel               0
loyalty_points_earned           0
loyalty_points_redeemed         0
quantity                        0
gross_sales                     0
discount_amount                 0
tax_amount                      0
shipping_cost                   0
net_sales                       0
product_cost                    0
profit                          0
profit_margin_percentage        0
customer_lifetime_value         0
is_repeat_customer              0
customer_order_count            0
order_year                      0
order_month                     0
order_month_name                0
order_quarter                   0
order_day                       0
order_day_name                  0
delivery_variance           24557
delivery_performance            0
calculated_profit_margin        0
margin_difference               0
dtype: int64

In [407]:
# Export cleaned datasets

orders.to_csv(
    "orders_clean.csv",
    index=False
)

order_items.to_csv(
    "order_items_clean.csv",
    index=False
)

product_catalog.to_csv(
    "product_catalog_clean.csv",
    index=False
)

customer_master.to_csv(
    "customer_master_clean.csv",
    index=False
)

print("All cleaned datasets exported successfully.")

All cleaned datasets exported successfully.